### ISSUE TITLE
The load example is broken

### ISSUE THREAD

**Issue by joelpurra** [ifandelse/machina.js#100]
After following the instructions to start the local server and navigating to the example page, it doesn't appear to do anything.

The domain `api.ihackernews.com` doesn't exist anymore. Should check http://ihackernews.com/ for updates.

**Comment by ifandelse** [comment]
@joelpurra Yes - I ran into this the other night when I was including the examples in the gh-pages branch. I will likely remove that example and try and introduce some of the more interesting FSM implementations my team at LeanKit has been using lately once I get some time. Thanks!

**Comment by joelpurra** [comment]
@ifandelse: haven't seen what it looks like, so not sure what I'm missing -- but if there are other, more interesting examples that'd be great!
