### ISSUE TITLE
Multiple child FSM

### ISSUE THREAD

**Issue by prok5reaper** [ifandelse/machina.js#105]
Hello,
I'd like to ask if it is possible to have more than one child FSMs in a parent FSM state. 

Thanks!

**Comment by ifandelse** [comment]
@prok5reaper Do you have a specific use case for which this is needed? I'd love to hear more to understand what the need is. Are you thinking that each child FSM would receive the input? Or only one of the children at a time, etc.?

**Comment by prok5reaper** [comment]
Hello again,

Well, all I really needed, was an FSM with two states, and each of them to have a child FSM. I didn't think very well of the design.

I'm sorry for the inconvenience.
