### ISSUE TITLE
Lodash 4.0.0

### ISSUE THREAD

**Issue by kevinkleine** [ifandelse/machina.js#115]
Hi there, 

First of all, cool lib! I use it all the time :)

Issue: it seems Lodash 4.0.0 breaks some Machina functionality, specifically the deferUntilTransition method.

**Comment by Pickachu** [comment]
:+1:

**Comment by lightkraken** [comment]
👍

**Comment by ifandelse** [comment]
@kevinkleine many apologies for taking _so long_ to reply (see #146). Once I've made a pass through current issues on the repo, I'll be making some updates to machina that will include a close look at lodash usage - so this will get fixed!
