### ISSUE TITLE
Transition event fired before _onEnter to state

### ISSUE THREAD

**Issue by laander** [ifandelse/machina.js#117]
I'm not sure whether this is a conscious design choice, but I'm having some timing problems. I want to observe when a states has been successfully transitioned to, as in, it's `_onEnter: fn()` has been called. The problem with the current `TRANSITION` event that's emitted, is that's it's fired _before_ the actual transition occurs. 

See here: https://github.com/ifandelse/machina.js/blob/master/lib/machina.js#L431

Am i missing something? If no, I would suggest adding a `TRANSITIONED` event too. This way, I can avoid clutter all my `_onEnter` functions with `this.emit('transitioned')` all over the place :+1:

**Comment by laander** [comment]
Upon further digging, there is a `HANDLED` event emitted after the transition has finished in the `.handle()` function. This is useful, but it still doesn't solve the problem as you need to know which action triggered the transition to listen in. Following the same for line of thought for handle, a `TRANSITIONED` event seems like an ever better idea.

(referencing #118 as it might be relevant as a short term solution)

**Comment by ifandelse** [comment]
@laander apologies for the _long silence_ on my part (see #146). The transitioned event was added and I just patched machina to fix an issue with it as well....
