### ISSUE TITLE
Using modular lodash approach to get smaller builds with webpack ?

### ISSUE THREAD

**Issue by riston** [ifandelse/machina.js#121]
The library seems great and powerful, but the problem I see for the web is lodash dependency which is the large one. Instead of requiring full lodash library could use the modular approach, there are actually around ~10 functions used from there. 

These could be just replaced with example:
`
// (great for smaller builds with browserify/webpack) 
var chunk = require('lodash/array/chunk'); 
`

There are also a separate method based builds also https://www.npmjs.com/browse/keyword/lodash-modularized.

**Comment by ifandelse** [comment]
@riston definitely agree with you on this (and apologies for the long delay....see #146 :-)). I plan to address this in the near future, thanks!
