### ISSUE TITLE
Using many instance of Behavioral FSM ?

### ISSUE THREAD

**Issue by barisvelioglu** [ifandelse/machina.js#123]
Hi,

I am going to use Behavioral FSM because I need more than one instance of it. But I dont know how many instances I am going to use. The instances will increase forever while the app lives. So how Behavioral FSM handles memory leak ?

I mean I created an instance to run on FSM and it finished its job. Then it will stay forever on memory ? Should I do something to dispose it ? 

Thanks

**Comment by edwinallenz** [comment]
I have the same use case. I also want to explore the idea of integrating with some persistence storage, any ideas of where to play with the code to implement this behaviour

**Comment by ifandelse** [comment]
@barisvelioglu I apologize for the long delay in replying (see #146). I'm not aware of any existing memory leaks in machina - of course that's always a risk. We'd have to look at specific use cases for me to have a more informed answer to your question. If code consuming machina is continually creating new instances of an FSM - the burden will be on the consuming code to remove references, (e.g. - event listener callbacks, etc.) that would keep it from getting GC'd (there's an existing method call to unsubscribe listeners). Beyond that, though, it will depend on how you use it in your own code. Regarding BehavioralFSMs, the intent is for one instance of a type of BehavioralFsm to exist, and the client state objects passed to it could be as many as you need (the FSM doesn't keep a handle to them). I can't think of a use case where spinning up multiple instances of the same BehavioralFsm makes sense.

**Comment by ifandelse** [comment]
@edwinallenz I'm so sorry for the long delay in replying (see #146). I'd considered baking some persistence hooks into machina and quickly abandoned it as it's a lot of responsibility to assume (and to generalize for). The good news is, as long as what you put on your client state objects is serializable, you could stick them in localStorage, or in redis or wherever you want, and then retrieve them and hand them back to the FSM as if nothing strange had happened. For example:

```javascript
const machina = require( "machina" );
const fs = require("fs");

const list = new machina.BehavioralFsm({
    namespace: "todolist",
    initialState: "ready",
    states: {
        ready: {
            next: "todo"
        },
        todo: {
            next: "doing"
        },
        doing: {
            next: "done"
        },
        done: {
            _onEnter( client ) {
                client.finishedOn = new Date();
            },
            next() {
                console.log( "I already made the donuts...." );
            }
        }
    },
    next( client ) {
        this.handle( client, "next" );
    }
});

let clientA = {};
let clientB = {};

list.next( clientA );
list.next( clientA );
list.next( clientA );
list.next( clientB );

fs.writeFileSync( "./clientA.json", JSON.stringify( clientA ) );
fs.writeFileSync( "./clientB.json", JSON.stringify( clientB ) );
clientA = null;
clientB = null;

let newClientA = JSON.parse( fs.readFileSync( "./clientA.json" ) );
let newClientB = JSON.parse( fs.readFileSync( "./clientB.json" ) );

list.next( newClientA );
list.next( newClientB );

console.log( "Client A state:", list.compositeState( newClientA ) );
console.log( "Client B state:", list.compositeState( newClientB ) );
```
