### ISSUE TITLE
handling events "once" ?

### ISSUE THREAD

**Issue by mikepuerto** [ifandelse/machina.js#129]
As there is no built in "once" event handler, is there any recommended way to achieve this?

**Comment by ifandelse** [comment]
@mikepuerto you could do something along these lines:

```javascript
var listener = someFsm.on("someEvent", function() {
    // do event handler-y things
    listener.off();
});
```

**Comment by ifandelse** [comment]
I'm going to close the issue, but feel free to follow up if you have more questions. I'll mark this for consideration in future features as well.
