### ISSUE TITLE
Transitioned event should fire even if _onEnter not defined

### ISSUE THREAD

**Issue by colegleason** [ifandelse/machina.js#137]
I use the "transitioned" even to watch for a successful transition. Some of my states do not need _onEnter functions, so this event does not fire. I currently just define an empty function in this case. It would be nice if the transitioned event fired regardless of _onEnter being defined, but always after _onEnter if it is defined.

**Comment by ifandelse** [comment]
Thanks for reporting this @colegleason - apologies for the delay in getting back to you on it. I'll look at getting this patched.

**Comment by ifandelse** [comment]
This will go out with 2.0.1

**Comment by joepie91** [comment]
Just a quick note: It seems that the changelog.md wasn't updated to reflect the recent 2.0.1 release :)

**Comment by rniemeyer** [comment]
@joepie91 - changelog.md updated. Thanks!

**Comment by joepie91** [comment]
Appreciated, thanks :)
