### ISSUE TITLE
Question: Reusing states actions in other states?

### ISSUE THREAD

**Issue by JeancarloFontalvo** [ifandelse/machina.js#138]
Hi, I'm new in _**Machina.js**_ (A very helpful tool, thanks for it Mister @ifandelse )
My question is dumb, I would like to know how I can reuse some actions for many states. I have a use case, where I have 4 states for a form view.

- **start**: I display all inputs and the user can edit them
- **tracking-editable**: I perform the same actions than the _**start**_ state
- **tracking-review**: I display all inputs, but  block some ones
- **closing**: Same as tracking-review, plus displaying new ones.

As you may see, maybe the last ones I could write, their own actions, but for the first two ones, I could reuse the actions.

So, _**is there a built-in way to do this?**_ Also, I'd like to know where I can find others tutorials using this marvelous tool with **form** and **conditional UI**. 

Thanks 😄

**Comment by ifandelse** [comment]
@JeancarloFontalvo I sincerely apologize for taking _so_ long to reply (see #146)! One simple way to re-use actions is to declare a function with the behavior you need and assign it to the relevant handlers. For example:

```javascript
function commonBehavior( fsm, ...args ) {
	// do stuff with args here....
}

let fsm = new machina.Fsm( {
	initialState: "state1",
	states: {
		state1: {
			handler1( ...args ) {
				// optionally do things specific to handler1
				// and then call into the common behavior
				commonBehavior( this, ...args );
			}
		},
		state2: {
			handler2( ...args ) {
				// optionally do things specific to handler1
				// and then call into the common behavior
				commonBehavior( this, ...args );
			}
		}
	}
} );
```

Hope that helps spark some ideas!
