### ISSUE TITLE
How to modularize machinaJS fsm with hundreds of states

### ISSUE THREAD

**Issue by salmansaifi7** [ifandelse/machina.js#143]
Hi Team,
I am writing an application which needs hundreds of states in FSM.
Is there any standard way of managing those states ? currently we have to write it in one single file, which is not good for production service.? I am looking for modularizing the states. 

I am expecting something like this..
fsm = new machina.Fsm();
fsm.addState(state1);
fsm.addState(state2);
fsm.addState(state3);
fsm.addState(state4);
fsm.addState(state5);

fsm.addHandler(handler1);
fsm.addHandler(handler2);
fsm.addHandler(handler3);
fsm.addHandler(handler4);

Please let me know i can achieve this.

**Comment by ifandelse** [comment]
@salmansaifi7 Apologies for the long delay in replying (see #146). I have a couple of thoughts - first, from a technical standpoint, sure, you can implement your own `addState` method to your FSM by doing something along these lines:

```javascript
const machina = require( "machina" );

const list = new machina.BehavioralFsm({
    namespace: "priorityTest",
    initialState: "ready",
    states: {
        ready: {
            next: "todo"
        }
    },
    next( client ) {
        this.handle(client, "next" );
    },
    addState( stateName, stateHandlers ) {
        if( this.states[ stateName ] ) {
            throw new Error("You've already added a state by that name");
            return;
        }
        this.states[stateName] = stateHandlers;
    }
} );

list.addState( "todo", { next: "doing" } );
list.addState( "doing", { next: "done" } );
list.addState( "done", { next() { console.log("We're already done"); } } );

let client = {};
list.next(client);
list.next(client);
list.next(client);
list.next(client); // We're already done
```

The second thought is that "hundreds of states" in an FSM is quite likely a code/design smell. I'd encourage you to look at whether or not these are either separate FSMs, or a state hierarchy.
