### ISSUE TITLE
Accepting multiple states for deferUntilTransition

### ISSUE THREAD

**Issue by joepie91** [ifandelse/machina.js#149]
Currently, `deferUntilTransition` only accepts a single 'target state', but there are quite a few usecases where there might be *multiple* valid target states, and an action should be deferred until whichever of those states is reached first.

__An example scenario:__ An embedded system uses machina.js for managing UI flows, and has multiple 'idle' screens depending on the time of day. It's scheduled to restart every 6 hours, but it should only restart if it is on one of the idle states; if it is in the middle of a user operation/transaction, it should wait until the transaction is completed and the UI has returned to an idle state before issuing the scheduled restart.

__Example (desired) code:__

```js
const machina = require("machina");

let stateMachine = new machina.Fsm({
	initialState: "idle",
	states: {
		idle: {
			_onEnter: function () {
				if (currentlyNight()) {
					this.transition("idleNight");
				} else {
					this.transition("idleDay");
				}
			},
		},
		idleNight: {
			restart: function () {
				/* ... */
			}
		},
		idleDay: {
			restart: function () {
				/* ... */
			}
		},
		startOperation: {
			...
		},
		...,
		"*": {
			restart: function () {
				this.deferUntilTransition(["idleNight", "idleDay"]);
			}
		}
	}
})
```

This should hopefully be a small change internally, checking whether the current state is in the provided list of states rather than just comparing with `===`.

Many thanks for the great library by the way, this is the first FSM library I've seen that's actually pleasant to work with :)

**Comment by ifandelse** [comment]
Thanks so much @joepie91 (both for the idea and the kind words). I definitely see how this could be useful - and seems simple to add. I'll take a look at adding here in the next few days.

**Comment by ifandelse** [comment]
Meant to note that this was taken care of in #150, thanks!
