### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by designtesbrot** [ifandelse/machina.js#169]
Hello @ifandelse,

first of all: thanks a lot for this FSM implementation. Here is a question in regards to licensing: I can see that the project is dual-licensed (MIT / GPL-2.0). I understand this as I am permitted usage of the source code under either MIT License or GPL-2.0 License (or as a logical "OR" instead of a logical "AND"). In other words, users of the source-code are free to choose whether to use it in an MIT-License Model or a GPL-2.0-License Model. Could you confirm/decline that this is the case and your intention? 

Thanks a lot

**Comment by ifandelse** [comment]
@designtesbrot apologies for the delay. The intent was to allow you to choose whichever license is most convenient (which for the vast majority of folks would be MIT, I'd imagine). Thanks!
