### ISSUE TITLE
Suggestions for the best way to provide persistence to the state of the FSM?

### ISSUE THREAD

**Issue by heckj** [ifandelse/machina.js#49]
My team was discussing the best way to provide persistence to an FSM extended from `machina.js` in the case where the process running the javascript code is killed and/or lost and restarted.

Do you have any suggestions for approaches or best places to "hook" into the FSM so that we can update some local persistence with it's state as it moves, and load in relevant state on startup if need be?

Our current thoughts are to write out some state identifier using the `onEnter: function() { ... }` and then setting `initialState` variable on the FSM from that persistence (if it exists) when we start up the FSM in the javascript loading code.

**Comment by edwinallenz** [comment]
@ifandelse Which do you think is the current best approach to provide persistence for machina right now?
