### ISSUE TITLE
Preserve stack trace for exceptions and perhaps use console.error

### ISSUE THREAD

**Issue by mnichols** [ifandelse/machina.js#54]
I can issue a PR if you want this. It's really a drag to lose our stack trace and would be nice to write to `console.error` if available:

```js
if ( console  ) {
    var logError = (console.error || console.log).bind(console)
    logError( exception.toString(),exception.stack  );
}
```

**Comment by ifandelse** [comment]
@mnichols - apologies for the delay in actually closing this. The stack is being logged now in the current version.
