### ISSUE TITLE
using machina as a state machine for multiple entities

### ISSUE THREAD

**Issue by jeff-collins** [ifandelse/machina.js#58]
I like the structure of the code that is written with machina.  I'd like to use it for a light document workflow.  The only problem is that obviously each document in the system will have its own state.  I can't see in the API a way to "restore" an instance of a FSM with the current state of a document on a document CRUD event and then let the state machine determine what to do next.  The API documentation says not to assign the "state" property directly.  Is there a way to essentially restore state to a FSM for a moment when a Document is modified by assigning its status field as the state of the FSM, call handle() on the FSM, and then restore it to the next Document's status that comes through, and call handle() on it again - this time in the context of the next Document's status field?

Other options I'm considering are - create the Fsm from scratch on every CRUD event, and dynamically make the initialState be the current state of the Document, but that would seem pretty heavy.  The other thought is to just call transition() artificially to set the state.  But since this is being done as a means to artificially "reset" the state on the FSM, it would mean that _onEnter() could not be easily used because it would be hard to tell the difference between an actual state transition as the result of an event, and just a restore. 

Any guidance is appreciated.

**Comment by ifandelse** [comment]
@jeff-collins when you get a chance, check out the v1.0.0-1 pre-release. The `BehavioralFsm` constructor lets you utilize the same FSM behavior for multiple "clients". The updated README talks a bit about this change as well as the wiki.

@dartmanx - apologies for the delay in replying to you! I understand the desire to cancel the transition in _onExit. I don't currently have plans to add that, however, similar behavior (if you still need it) could be achieved by using a constraint-based FSM. An example of this can be seen in [this discussion](https://github.com/ifandelse/machina.js/issues/4#issuecomment-5110351). Thanks :)
