### ISSUE TITLE
Allow handlers to return values?

### ISSUE THREAD

**Issue by Codelica** [ifandelse/machina.js#62]
Hello,

Excellent work!  I've been using machina as part of a small node module to abstract/simplify interfacing to some older SOAP/WSDL based services we have to work with.  Hoping to program away the pain into something tolerable for us to use. :)

Everything has been working well, except one snag I haven't been able to reason around.  Basically I'd like the handlers (machina handle() calls) to be able to return values in order to simplify things like conditional followup steps/transitions (outside the handler) or returning promises for chaining.

This is the quick change I've been using so far:
**commit removed - see below**  will update with proper pull request.

So, I guess my questions are just this.   

1) Does this seem like a reasonable addition, or am I a better way or potential problem?
2) If it does seem reasonable, would you consider the change?

Thanks in advance...

-James

**Comment by paulpdaniels** [comment]
It may also be useful to update the docs to reflect this change.  I didn't realize this was a feature until looking through the source code.

**Comment by ifandelse** [comment]
Sorry @paulpdaniels. I will add that to my list of changes I'm working thru locally. FWIW, I regret adding this but don't intend to rip it out. v0.5 will support hierarchical and behavioral FSMs, in which return values likely won't be supported (but the current machina.Fsm will still support it if it's not in a hierarchy)

**Comment by ifandelse** [comment]
@paulpdaniels I made a note of this on the README - and hope to expand a bit more when I add input handler examples to the wiki.
