### ISSUE TITLE
Log exception trace instead of string

### ISSUE THREAD

**Issue by igncp** [ifandelse/machina.js#67]
Hi there,

I bring one suggestion to the table. I am working with your library and when an exception appears, only the string of the exception is logged (src/fsm.js, line 21). In our case and for development, showing the entire trace would make our life easier, because it would show the file and line number. For example, in line 21 of fsm.js:

`console.log(exception.stack);`

Opinions?

**Comment by ifandelse** [comment]
This is now in the current version, thanks!

**Comment by igncp** [comment]
Thanks for the heads up!
