### ISSUE TITLE
Be able to export state machine diagram

### ISSUE THREAD

**Issue by oliverzy** [ifandelse/machina.js#76]
Hi Author,

The library is in pretty good shape, I would like to use it in our project. My question is that is there any plan to support exporting state machine diagram?

The state machine diagram is very useful in documentation and also be able to communicate with non-technical people.

**Comment by ifandelse** [comment]
@oliverzy Actually this is something I've thought about, though I haven't spiked out any ideas yet. If you've come across any decent chart-producing JS libs that you like, let me know. :smile:

**Comment by oliverzy** [comment]
I recommend JointJS. FSM support is builtin. See this example: http://www.jointjs.com/demos/fsa
JointJS is based on svg, I think it's better than static image.

**Comment by oliverzy** [comment]
After playing with the library, I found it seems hard to export a diagram for machina because machina doesn't explicitly define transition end state when the value of inputType is a function not a string.

**Comment by ifandelse** [comment]
Closing this for now - it would be a nice-to-have option at some point, so I may try to revisit it later.
