### ISSUE TITLE
universal handler

### ISSUE THREAD

**Issue by javaknight** [ifandelse/machina.js#80]
Would be nice to have a universal handler you can apply to all states. EG: 
_reset: function() { this.transition('uninitialized'); }

**Comment by ifandelse** [comment]
The `_reset` input name is already used in machina, please see the docs on [hierarchical FSMs](https://github.com/ifandelse/machina.js/wiki/HierarchicalFsm).

machina already has a lookup fallback approach for how to find handlers. First it checks the state object for the named input handler. If it doesn't find one, it looks for the catch-all handler in the state object. if it doesn't find either, it checks for an instance/prototype member by the same name on the FSM, and finally checks for a catch-all handler at the FSM instance level as well. See https://github.com/ifandelse/machina.js/blob/master/lib/machina.js#L383 for part of this logic.
