### ISSUE TITLE
Update lodash version

### ISSUE THREAD

**Issue by hfaulds** [ifandelse/machina.js#83]
Trying to use Machina in a web worker.

This doesn't work because of the outdated lodash version in the machina 

```
"dependencies": {
    "lodash": "~2.4.1"
  },
```

See https://github.com/lodash/lodash/issues/313). It is fixed in v3 of lodash (https://github.com/lodash/lodash/issues/313#issuecomment-71367990).

**Comment by eternalko** [comment]
This also holds true for Postal.js

**Comment by ifandelse** [comment]
@hfaulds I'll try and get this updated ASAP. Postal has already moved to [lodash 3.1.0](https://github.com/postaljs/postal.js/blob/master/package.json#L85)

**Comment by eternalko** [comment]
To truly fix this there is a need to merge with lodash 3.4.1. I will write
back here when the fix is ready.

**Comment by ifandelse** [comment]
@eternalko - I already have the dependency version bumps in process, should be up today.

**Comment by ifandelse** [comment]
@eternalko @hfaulds I've updated to v3.3.1. Thanks!

**Comment by eternalko** [comment]
@ifandelse, ur welcome

**Comment by hfaulds** [comment]
@ifandelse Thanks for the quick fix and pre-release!
