### ISSUE TITLE
Missing handler argument to fallback(*) input handler breaks on IE11

### ISSUE THREAD

**Issue by javaknight** [ifandelse/machina.js#84]
The bug doesn't happen on Chrome. Haven't tried other browsers.

Environment: 
1. meteor latest release
2. machina.js latest release

Steps to reproduce:
1. Create a new finite state machine with var myFSM = new machina.Fsm ... as normal.
2. Create the uninitialized state as normal. Set the initial state as unitialized
3. Create a new state, call it test
4. Give the new state test a '*' fallback input handler and no other input handlers.
    'myTestState' : {
    '*' : function() {  
        console.log('Hi');
     }
5. Give the FSM an API handle that calls the test state like so
    apiTest: function(arg)
    {
      this.transition('myTestState');
      this.handle(arg);
    }
6. Call your api like so [NOTE: neglecting to supply arg on purpose.]
    myFSM.apiTest();

Expected result:
    Console log emits Hi on IE
Result on Chrome: 
    Console log emits Hi on Chrome
Result on IE:
    Throws javascript exception
Relevant stack trace
Unable to get property 'ticket' of undefined or null
areich_machina.js:413:21
areich_machina.js:612:13

**Comment by ifandelse** [comment]
@javaknight The above example fails to pass an actual input to the FSM and, instead, effectively calls `this.handle(undefined)`. That's not something an FSM would understand. I can look at throwing a more specific exception with a descriptive message.

**Comment by ifandelse** [comment]
Got a specific exception error for this in master. Will go out once the next version gets tagged.
