### ISSUE TITLE
Why state machine is not so popular in web?

### ISSUE THREAD

**Issue by quolpr** [ifandelse/machina.js#85]
I think, that State Machine - is a great pattern for developing web pages. I found it easy to build a complex form with a huge logic by using your library. The code becomes easy to understand and it is easy to add new functionality. But why there are few articles about State Machine? Why it is not so popular?

P.s.: author, thank you for this library, you did a very huge work.

**Comment by ifandelse** [comment]
@quolpr Thank you very much! It's always encouraging to hear that machina helped someone out. :smile:

I've wondered the same as well (as to why the pattern isn't as popular in front-end dev). I think one possible explanation is that if you're brand new to programming overall, there's a lower barrier-to-entry in learning basic web development. A lot of developers that start out that way (of which I was one back in 1999), don't usually get exposed to more formal pattern knowledge until they get into server-side development (or something other than web). This seems to be changing slightly, with the rise of JavaScript UI frameworks in general...though that also comes with its own baggage! :grinning:

**Comment by netaisllc** [comment]
Agree.  And more's the pity. The very nature complex UIs demands precise
management of state. I'm glad I found the project.

On Wed, Apr 1, 2015 at 10:02 AM, Jim Cowart <notifications@github.com>
wrote:

> @quolpr <https://github.com/quolpr> Thank you very much! It's always
> encouraging to hear that machina helped someone out. [image: :smile:]
>
> I've wondered the same as well (as to why the pattern isn't as popular in
> front-end dev). I think one possible explanation is that if you're brand
> new to programming overall, there's a lower barrier-to-entry in learning
> basic web development. A lot of developers that start out that way (of
> which I was one back in 1999), don't usually get exposed to more formal
> pattern knowledge until they get into server-side development (or something
> other than web). This seems to be changing slightly, with the rise of
> JavaScript UI frameworks in general...though that also comes with its own
> baggage! [image: :grinning:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ifandelse/machina.js/issues/85#issuecomment-88548848>.
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>

**Comment by murillo128** [comment]
FWIW, I am exactly machina.js exactly for us, but found that some of the restrictions for keepings correctness at theorical level on the library made it harder for me to use the it without mods. Bainly be able to have state attributes, which provide a kind of parametrizable-states or state-templates, which also requires me to allow transitioning to same state (but with different attrs).

Anyway, a great project.

**Comment by quolpr** [comment]
I found, that machina.js don't provide asynchronous action when state is changing. So, I want to make pull request as soon as possible to provide this functionality. 
And, so on, I think, it depends on PR. I will write post on habrahabr.ru (it is very popular russian IT site), to make it more accessible.

**Comment by ifandelse** [comment]
@quolpr I'd need to see an example use case to better understand what you mean by "machina.js don't provide asynchronous action when state is changing". The `transition` call itself is synchronous, but the invocation of `transition` inside an input handler can be invoked asynchronously. In addition, there are built-in events for listening to transitions, and you can emit custom events as well, depending on what your needs are. If I can see an example use case (or psuedo code) that better describes what you mean it would help me understand if it's something I can add support for. Thanks!

**Comment by demisx** [comment]
I think there is a lack of tutorials on engaging state machines in frontend and programming in general, so it creates pseudo perception that state machines are complicated and have limited application. I am currently using states (via Angular UI router) for UI interactions. However, I also have models that follow certain workflows. For example, an `ad` model in a classified starts of as a draft, then it is published, then it expires after N number of days. When expired, it can be reactivated. On the contrary, when an ad is deactivated by the filtering algorithm, it cannot be reactivated and so on. Do you think machina.js state machine would be a good choice to manage this kind of workflow? Or is it an overkill?

**Comment by ifandelse** [comment]
@demisx Apologies for the delay in replying. I personally don't think it's overkill (of course, I'm biased, in that I'm using machina for these sorts of scenarios already). That's not to say it can't be handled with other approaches (or with hand-rolled state machines). Definitely interested to hear how it's working for you if you're using it like this.
