### ISSUE TITLE
Link to github repo on machina-js.org throws frame error

### ISSUE THREAD

**Issue by alampros** [ifandelse/machina.js#86]
Chrome 42.0.2311.68 beta (64-bit) throws this error when clicking on the "View on GitHub" link:
```
Refused to display 'https://github.com/ifandelse/machina.js' in a frame because it set 'X-Frame-Options' to 'deny'.
```

The button:
![screen shot 2015-04-02 at 12 50 19 pm](https://cloud.githubusercontent.com/assets/297461/6968728/dee237ac-d936-11e4-92eb-887486b0d604.png)

**Comment by ifandelse** [comment]
Should work now, thanks!
