### ISSUE TITLE
Use a syntax highlighter on homepage

### ISSUE THREAD

**Issue by alampros** [ifandelse/machina.js#87]
Just a suggestion – most of the page's content is code and it looks daunting and complicated without good syntax highlighting. [Jekyll has built in pygments highlighting](http://jekyllrb.com/docs/templates/#code-snippet-highlighting) or you can use something like [Prism.js](http://prismjs.com/).

**Comment by demisx** [comment]
+1 https://demisx.github.io/jekyll/2014/01/13/improve-code-highlighting-in-jekyll.html

**Comment by ifandelse** [comment]
Thanks for giving me a heads up that the gh-pages weren't showing syntax highlighting! Not sure what went wrong, but when I re-generated them, it seemed to work this time.
