### ISSUE TITLE
Question about Fsm definition in source code

### ISSUE THREAD

**Issue by igncp** [ifandelse/machina.js#90]
Hi,

When looking into the Fsm definition, there is some code repetition in some methods (e.g. handle, transition, etc.). Maybe it would be nice to change the definition of some methods so it is more clear and expressive their common relation. I added a gist to show what I mean (all tests passing):

https://gist.github.com/igncp/071632ed5d6fa4d7f8d0

Maybe I am missing some drawbacks of the change. What do you think about this change in terms of architectural improvement or deterioration?

**Comment by ifandelse** [comment]
Hi @igncp, I apologize for the delay in replying. I'll check out the gist and post back here once I've had a moment to review and try it out, thanks!

**Comment by ifandelse** [comment]
@igncp I don't have any problem with this change - I think it cleans up quite a bit of the repetition I have in the current version. You up for opening a PR containing this update?
