### ISSUE TITLE
Error when building machina

### ISSUE THREAD

**Issue by singlebarrelwhiskey** [ifandelse/machina.js#94]
On my linux machine, I had to rename src/fsm.js to src/Fsm.js in order to successfully build.
Is it suppose to build with fsm.js?

**Comment by mondwan** [comment]
So do I. Any update for this status yet? (V1.1.0)

**Comment by ifandelse** [comment]
@singlebarrelwhiskey @mondwan Apologies! I'll see if I can take care of this tonight or tomorrow. Not.enough.hours.in.the.day. :smile:

**Comment by ifandelse** [comment]
Fixed in v1.1.1, thanks!
